version: '3.3'
services:
  db:
    image: mysql:5.7
    deploy:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
  wait:
    build:
      context: .
      args:
        RELEASE_VERSION: 0.1.1
    command: "wait-go --wait \"db:3306\" --command \"ls -al\""